apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flask-app
  # name: flask-hello
spec:
  selector: 
    matchLabels:
      app: flask-app
  replicas: 2
  template:
    metadata:
      labels: 
        app: flask-app
    spec:
      containers: 
      - name: flask-app
        image: vigneshkathirkamar/hello:0.0.1
        # image: vigneshkathrikamar/flaskhello
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
